create table if not exists statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar,
    uri varchar,
    ip varchar,
    request_date timestamp WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS uris_index ON statistics(uri);